version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: isl_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: isl_features
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: isl_fastapi_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/isl_features
      - SQLITE_FALLBACK=False
      - HOST=0.0.0.0
      - PORT=8000
      - SECRET_KEY=94e7bd016f4d2f0907d72138a0a86071efc5625bf9c9d5e3ef544b802a4d3ff5
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/workspace

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: isl_react_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
